#!/bin/sh

if ! command -v "jshon" >/dev/null 2>&1; then
    printf "%s\\n" "you need to install 'jshon' to run this program" >&2
    exit 1
fi

if ! command -v "rofi" >/dev/null 2>&1; then
    printf "%s\\n" "you need to install 'rofi' to run this program" >&2
    exit 1
fi

# Save current workspace name
WORKSPACE="$(i3-msg -t get_workspaces | jshon -a -e focused -u -p -e name -u | awk 'f{print;f=0} /true/{f=1}')"

# Switch to window
rofi -show window

# Move selected to previous worspace
i3-msg "move container workspace ${WORKSPACE}"

# Switch to that workspace
i3-msg "workspace ${WORKSPACE}"
